src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $participants = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\ManyToMany(targetEntity: EventCategory::class, inversedBy: 'events')]
    private Collection $category;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $attachmentFilename = null;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getParticipants(): ?int
    {
        return $this->participants;
    }

    public function setParticipants(int $participants): static
    {
        $this->participants = $participants;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * @return Collection<int, EventCategory>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(EventCategory $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(EventCategory $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getAttachmentFilename(): ?string
    {
        return $this->attachmentFilename;
    }

    public function setAttachmentFilename(?string $attachmentFilename): static
    {
        $this->attachmentFilename = $attachmentFilename;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\EventCategory;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('name', TextType::class, [
            'attr' => [
                'class' => 'form-control',
                'placeholder' => 'Event name...',
            ],
            'constraints' => [
                new Constraints\NotBlank()
            ],
            'label' => 'Name *',
        ])
        ->add('description', TextareaType::class, [
            'attr' => [
                'class' => 'form-control',
                'placeholder' => 'Description...',
            ],
            'required' => false,
        ])
        ->add('participants', IntegerType::class, [
            'attr' => [
                'class' => 'form-control',
                'placeholder' => 'Number of participants'
            ],
            'label' => 'Participants *',
        ])
        ->add('category', EntityType::class, [
            'attr' => [
                'class' => 'form-control',
            ],
            'class' => EventCategory::class,
            'choice_label' => 'name',
            'required' => false,
            'multiple' => true,
            'expanded' => true,
        ])

        ->add('start_date', DateTimeType::class, [
            'attr' => [
                'class' => 'form-control',
                'placeholder' => 'dd/MM/yyyy HH:mm'
            ],
            'constraints' => [
                new Constraints\NotBlank(),
            ],
            'label' => 'Start date *',
            'html5' => false,
            'widget' => 'single_text',
            'format' => 'dd/MM/yyyy HH:mm',
        ])
        ->add('end_date', DateTimeType::class, [
            'attr' => [
                'class' => 'form-control',
                'placeholder' => 'dd/MM/yyyy HH:mm'
            ],
            'label' => 'End date *',
            'constraints' => [
                new Constraints\NotBlank(),
                new Constraints\GreaterThan([
                    'propertyPath' => 'parent.all[start_date].data'])
            ],
            'html5' => false,
            'widget' => 'single_text',
            'format' => 'dd/MM/yyyy HH:mm',
        ])
        ->add('attachment_filename', FileType::class, [
            'label' => 'Attachment (PDF file)',
            'mapped' => false,
            'required' => false,
            'constraints' => [
                new Constraints\File([
                    'maxSize' => '4096k',
                    'mimeTypes' => [
                        'application/pdf',
                        'application/x-pdf',
                    ],
                    'mimeTypesMessage' => 'Please upload a valid PDF document',
                ])
            ],
            'attr' => [
                'class' => 'form-control',
            ],
        ])
        ->add('save', SubmitType::class, [
            'attr' => [
                'class' => 'btn btn-primary mx-auto col-3'
            ]
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/Event/EventActionController.php
<?php

namespace App\Controller\Event;

use App\Entity\Event;
use App\Service\EventFormHandler;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventActionController extends AbstractController
{
    #[Route('/events/{id}/edit', name: 'event_edit')]
    public function edit(Event $event, Request $request, EventFormHandler $formHandler): Response
    {
        $form = $formHandler->handleSubmitForm($request, $event);
        if ($formHandler->isSubmitted) {
            $this->addFlash('success', 'Event updated');
            return $this->render('event/details.html.twig', [
                'event' => $event
            ]);
        }
        return $this->render('event/edit.html.twig', [
            'form' => $form
        ]);
    }
    #[Route('/events/{id}/delete', name: 'event_delete')]
    public function delete(EntityManagerInterface $entityManager, Event $eventId): Response
    {
        $repository = $entityManager->getRepository(Event::class);
        $event = $repository->find($eventId);
        $entityManager->remove($event);
        $entityManager->flush();
        return $this->redirectToRoute('app_administration');
    }
}

src/Controller/Event/EventController.php
<?php

namespace App\Controller\Event;

use App\Entity\Event;
use App\Service\EventFormHandler;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    public function index(Request $request, EventFormHandler $formHandler): Response
    {
        $form = $formHandler->handleSubmitForm($request);
        if ($formHandler->isSubmitted) {
            $this->addFlash('success', 'Event added');
            return $this->render('event/details.html.twig', [
                'event' => $formHandler->event
            ]);
        }
        return $this->render('event/index.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/events', name: 'app_events')]
    public function events(Request $request, EventFormHandler $formHandler): Response
    {
        $result = $formHandler->handleFilter($request);
        return $this->render('event/events.html.twig', [
            'form' => $result['form'],
            'count' => $result['count'],
            'participants' => $result['participants'],
            'pager' => $result['pager'],
        ]);
    }
    #[Route('/administration', name: 'app_administration')]
    public function administration(Request $request, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Event::class);
        $queryBuilder = $repository->createQueryBuilder('event');
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->get('page', 1),
            10
        );

        $events = $repository->findAll();
        return $this->render('event/administration.html.twig', [
            'pager' => $pagerfanta
        ]);
    }
    #[Route('event/{id}', name: 'app_details')]
    public function details(Event $event): Response
    {
        return $this->render('event/details.html.twig', [
            'event' => $event
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $event = $form->getData();
            $entityManager->persist($event);
            $entityManager->flush();

            $this->addFlash('success', 'Event added ');
        }

        return $this->render('event/index.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/events', name: 'app_events')]
    public function events(EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Event::class);
        $events = $repository->findAll();
        return $this->render('event/events.html.twig', [
            'events' => $events
        ]);
    }
    #[Route('/administration', name: 'app_administration')]
    public function administration(EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Event::class);
        $events = $repository->findAll();
        return $this->render('event/administration.html.twig', [
            'events' => $events
        ]);
    }
    #[Route('/events/{id}/edit', name: 'event_edit')]
    public function edit(): Response
    {
        return $this->redirectToRoute('app_events');
    }
    #[Route('/events/{id}/delete', name: 'event_delete')]
    public function delete(): Response
    {
        return $this->redirectToRoute('app_events');
    }
}

templates/event/administration.html.twig
{% extends 'base.html.twig' %}
{% block title %}Administration{% endblock %}
{% block body %}
<div class="container">
<h4 class="card-title mt-3 mb-3 text-center">Administration</h4>
  <nav aria-label="Page navigation example">
   <ul class="pagination justify-content-center">
  {{ pagerfanta(pager) }}
  </ul>
  </nav>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Participants</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for event in pager %}
      <tr>
        <td>{{ event.name }}</td>
        <td>{{ event.description }}</td>
        <td>
          {% for category in event.category %}
            {{ category.name }}
            {% if not loop.last %},{% endif %}
          {% endfor %}
        </td>

        <td>{{ event.participants }}</td>
        <td>{{ event.startDate|date('d/m/Y\\ H:i') }}</td>
        <td>{{ event.endDate|date('d/m/Y\\ H:i') }}</td>
          <td>
            <a href="{{ path('event_edit', {'id': event.id}) }}" class="btn btn-primary">Edit</a>
            <a href="{{ path('event_delete', {'id': event.id}) }}" class="btn btn-danger">Delete</a>
          </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

templates/event/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event Details{% endblock %}

{% block body %}
  <div class="container mb-5">
    <div class="card">
      <div class="card-header">
        <h2>{{ event.name }}</h2>
      </div>
      <div class="card-body">
        <p class="card-text">
          <strong>Description:</strong> {{ event.description }}
        </p>
        <p class="card-text">
          <strong>Participants:</strong> {{ event.participants }}
        </p>
        <p class="card-text">
          <strong>Start Date:</strong> {{ event.startDate|date('Y-m-d H:i') }}
        </p>
        <p class="card-text">
          <strong>End Date:</strong> {{ event.endDate|date('Y-m-d H:i') }}
        </p>
        <p class="card-text">
        <strong>Categories:</strong>
          {% for category in event.category %}
            {{ category.name }}
            {% if not loop.last %},{% endif %}
          {% endfor %}
        </td>

        <p class="list-group-item">
          <strong>Duration:</strong>

          {% set difference = date(event.endDate).diff(date(event.startDate)) %}

          {% if difference.format('%y') > 0 %}
            {{ difference.format('%y years, %m months, %d days, %h hours, %i minutes') }}
          {% elseif difference.format('%m') > 0 %}
            {{ difference.format('%m months, %d days, %h hours, %i minutes') }}
          {% elseif difference.format('%d') > 0 %}
            {{ difference.format('%d days, %h hours, %i minutes') }}
          {% else %}
            {{ difference.format('%h hours, %i minutes') }}
          {% endif %}
        </p>
        {% if event.attachmentFilename %}
          <a href="{{ asset('uploads/attachments/' ~ event.attachmentFilename) }}">View attachment (PDF)</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit{% endblock %}

{% block body %}

<div class="container">
<h4 class="card-title mt-3 text-center">Edit Event</h4>
  <div class="card">
    <div class="card-body">
        {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.participants) }}

        {{ form_label(form.start_date) }}
        <div class="input-group" />
          {{ form_widget(form.start_date) }}
          <span
            class="input-group-text"
            data-td-target="#datetimepicker1"
            data-td-toggle="datetimepicker"
          >
            <i class="fas fa-calendar"></i>
          </span>
        </div>
        {{ form_label(form.end_date) }}
        <div class="input-group" />
        {{ form_widget(form.end_date) }}
        <span
          class="input-group-text"
          data-td-target="#datetimepicker1"
          data-td-toggle="datetimepicker"
        >
        <i class="fas fa-calendar"></i>
        </span>
        </div>
        {{ form_row(form.attachment_filename) }}
        {{ form_label(form.category) }}
        <div class="input-group">
          {% for category in form.category %}
        <div class="form-check form-check-inline">
            {{ form_widget(category, {'attr': {'class': 'form-check-input'}}) }}
            {{ form_label(category) }}
        </div>
          {% endfor %}
        </div>
    </div>
  </div>
{{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('index') }}
{% endblock %}

templates/event/events.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events{% endblock %}

{% block body %}

<div class="container">
<div class="card mx-auto bg-light" style="max-width: 600px">
<div class="card-body">
<h4 class="card-title mt-3 text-center">Filter events</h4>
{{ form_start(form) }}
      {% for child in form %}
        <div class="form-group mt-2 mx-auto">
          {{ form_row(child) }}
        </div>
    {% endfor %}
{{ form_end(form) }}

  </div>
  </div>
  <nav aria-label="Page navigation example">
   <ul class="pagination justify-content-center mt-4">
  {{ pagerfanta(pager) }}
  </ul>
  </nav>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Participants</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
    {% for event in pager %}
    <tr>
      <td>{{ event.name }}</td>
      <td>{{ event.description }}</td>
      <td>
      {% for category in event.category %}
        {{ category.name }}
        {% if not loop.last %},{% endif %}
      {% endfor %}
      </td>
      <td>{{ event.participants }}</td>
      <td>{{ event.startDate|date('d/m/Y\\ H:i') }}</td>
      <td>{{ event.endDate|date('d/m/Y\\ H:i') }}</td>
      <td> <a href="{{ path('app_details', {'id': event.id}) }}" class="btn btn-primary">View</a> </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    <div class="row mt-2">
      <div class="col-md-6">
        <h6 class="mb-0">Total Results: {{ count }}</h6>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-md-6">
        <h6 class="mb-0">Total participants: {{ participants }}</h6>
      </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('filter') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
<div class="container my-auto h-100">
  <div class="card justify-content-center mx-auto bg-light p-4 my-auto" style="max-width: 800px">
  <h4 class="card-title text-center">New Event</h4>
    <div class="card-body">
        {{ form_start(form) }}
        <div class="form-group">
          {{ form_row(form.name) }}
        </div>
        <div class="form-group mt-2">
          {{ form_row(form.description) }}
        </div>
        <div class="form-group mt-2">
          {{ form_row(form.participants) }}
        </div>

        <div class="form-group mt-2">
          {{ form_label(form.start_date) }}
          <div class="input-group" />
            {{ form_widget(form.start_date) }}
            <span
              class="input-group-text"
              data-td-target="#datetimepicker1"
              data-td-toggle="datetimepicker"
            >
              <i class="fas fa-calendar"></i>
            </span>
          </div>
          {{ form_errors(form.start_date) }}
        </div>
        <div class="form-group mt-2">
        {{ form_label(form.end_date) }}
        <div class="input-group" />
        {{ form_widget(form.end_date) }}
        <span
          class="input-group-text"
          data-td-target="#datetimepicker1"
          data-td-toggle="datetimepicker"
        >
        <i class="fas fa-calendar"></i>
        </span>
        </div>
          {{ form_errors(form.end_date) }}
        </div>
        <div class="form-group mt-2">
          {{ form_row(form.attachment_filename) }}
        </div>
        {{ form_label(form.category) }}
        <div class="input-group mt-2">
          {% for category in form.category %}
        <div class="form-check form-check-inline">
            {{ form_widget(category, {'attr': {'class': 'form-check-input'}}) }}
            {{ form_label(category) }}
        </div>
          {% endfor %}
        </div>
        <div class="input-group mx-auto mt-4">
        {{ form_widget(form.save) }}
        </div>
    </div>
  </div>
{{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('index') }}
{% endblock %}